stages:
  - test
  - build

test-job:
  image: node:22-alpine
  stage: test
  tags:
    - kai-home
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Running basic test..."
    - |
      node <<EOF
      const http = require('http');
      http.get('http://localhost:8080', res => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (!data.includes('Welcome to DevOps course!')) {
            console.error('Test failed: Expected string not found');
            process.exit(1);
          }
          console.log('Test passed ✅');
        });
      }).on('error', () => {
        console.error('Test failed: Server is not responding');
        process.exit(1);
      });
      EOF

build-job:
  #используем стандартный dind:24 image
  stage: build
  tags:
    - kai-home
  script:
    - docker build -t devops_hello:$CI_PIPELINE_ID .
