stages:
  - build
  - test
  - containerize
  - deploy

build-job:
  image: node:22-alpine
  stage: build
  tags:
    - kai-home
  cache:
    key: npm-cache
    paths:
      - node_modules/
      - dist/
  script:
    - echo "Building the application..."
    - npm ci
    - npm run build

test-job:
  image: node:22-alpine
  stage: test
  tags:
    - kai-home
  cache:
    key: npm-cache
    paths:
      - node_modules/
      - dist/
  script:
    - echo "Running basic test..."
    - node app.js &
    - sleep 5
    - |
      node <<EOF
      const http = require('http');
      http.get('http://localhost:8080', res => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (!data.includes('Welcome to DevOps course!')) {
            console.error('Test failed: Expected string not found');
            process.exit(1);
          }
          console.log('Test passed ✅');
        });
      }).on('error', () => {
        console.error('Test failed: Server is not responding');
        process.exit(1);
      });
      EOF

containerize-job:
  image: docker:24-dind
  stage: containerize
  tags:
    - kai-home
  dependencies: [] # Отключаем автоматическую загрузку артефактов
  script:
    - docker build -t $DOCKERHUB_USERNAME/devops_hello:$CI_PIPELINE_ID .
    - docker push $DOCKERHUB_USERNAME/devops_hello:$CI_PIPELINE_ID

deploy-job:
  stage: deploy
  tags:
    - kai-home
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - export DOCKER_HOST="ssh://$DEPLOY_USER@$DEPLOY_HOST"
    - docker ps # Test connection
    - docker pull "$DOCKERHUB_USERNAME/devops_hello:$CI_PIPELINE_ID"
    - docker stop devops_hello || true
    - docker rm devops_hello || true
    - docker run -d --name devops_hello -p 8080:8080 "$DOCKERHUB_USERNAME/devops_hello:$CI_PIPELINE_ID"
